#!/usr/bin/env python
# coding: utf-8

# In[1]:


import numpy as np
a=np.arange(12).reshape(3,4)


# In[2]:


a


# In[7]:


for row in a:
    for cell in row:
        print(cell)
    


# In[ ]:




