#!/usr/bin/env python
# coding: utf-8

# In[39]:


name=input("enter your username here: ")
if name=="sathish":
    pwd=input("if your really sathish whats the password! ")
    if pwd== "minuts#123":
        print("haha, i knew it was you all along " + name)
    else:
        print("password you entered is incorrect")
    
    
        
        


# In[ ]:





# In[ ]:




